### ISSUE TITLE
Feature request: Ability to change default font

### ISSUE THREAD

**Issue by Mythos** [Hydra-Mods/Gathering#2]
I really would like to see an option to choose a font (in my case Roboto-Medium) as I'm having difficulties reading the text from Gathering. (UI scaling is set to 0.55 in ElvUI, but the font is also a bit narrow)

**Comment by Hydra-Mods** [comment]
A GUI to change visual aspects of the addon is very likely to be the next change for Gathering

**Comment by Mythos** [comment]
Thats great to hear! :-)
