### ISSUE TITLE
Feature request: Show both items & gold per hour

### ISSUE THREAD

**Issue by Mythos** [Hydra-Mods/Gathering#3]
I already wanted to create a bug report as the gold per hour wasn't showing up, until I noticed I have to press SHIFT for that.
It would be really nice to have both information visible at the same time, next to each other.

**Comment by Hydra-Mods** [comment]
I feel like this is going to be very wide. I can test it, but I'm unsure. Down the road I will probably make a custom window rather than using a tooltip anyways

**Comment by Mythos** [comment]
I'm not sure how scaling applies to this, as I've set my ElvUI to scale to 0.55 (having a 27" FullHD screen ca. 30cm in front of me helps with that).

I've added a screenshot of how it looks on my machine right now.

![image](https://user-images.githubusercontent.com/416568/84587762-5ff16c80-ae22-11ea-89dc-85b53d30e6cd.png)
